"""
config/model_roadmap.py
=======================
Structured registry of PDF-style content modules with traceability fields.

Every item includes evidence_basis, data_source_status, and can_render_real_chart.
"""
from __future__ import annotations

ROADMAP: list[dict] = [
    # ── 00 · Liquidity ──
    {"section": "00", "module_id": "cli_index", "title": "Composite Liquidity Index",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "index/composite.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SOFR", "EFFR", "IORB", "IG OAS", "HY OAS", "Fed reserves"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Core proprietary model. Do not modify."},

    # ── 01 · Policy ──
    {"section": "01", "module_id": "policy_spot", "title": "Policy spot rates & funding spreads",
     "app_section": "01", "reference_section": "01 · Policy & Short Rates",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/policy_short_rates.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SOFR", "EFFR", "IORB", "TGCR", "BGCR", "GCF", "TPR"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live confirmed spot-rate and funding-spread monitor. The fixed-contract SOFR strip is a separate live module; a meeting-by-meeting FOMC path remains blocked pending the FOMC calendar and day-weighted probability methodology."},
    {"section": "01", "module_id": "fomc_path", "title": "FOMC implied policy path",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "roadmap only", "data_source_status": "partial",
     "can_render_real_chart": False,
     "required_data": ["FF futures", "FOMC calendar", "EFFR"],
     "missing_data": ["FOMC meeting calendar", "Contract metadata/conventions"],
     "recommended_priority": 5,
     "build_notes": "The fixed quarterly SFR strip is Live with eight actual contract months. A meeting-by-meeting FOMC path remains unimplemented because the FOMC calendar, day-weighted meeting-month methodology and probability framework are not supplied."},
    {"section": "01", "module_id": "sofr_strip", "title": "SOFR Futures Strip & Calendar Spreads",
     "app_section": "01b", "reference_section": "01 · Policy & Short Rates",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/policy_futures_strip.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Policy_Futures sheet", "SFRU6 through SFRM8 fixed quarterly contracts"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live fixed-contract Three-Month SOFR strip using eight quarterly contracts from SEP 26 to JUN 28. Includes implied rates, calendar spreads and terminal diagnostics. It is not a meeting-by-meeting FOMC probability model."},

    # ── 02 · Rate Decomposition ──
    {"section": "02", "module_id": "us_curve_complex", "title": "US Curve Complex",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["US nominal 2Y/5Y/10Y/30Y", "US breakeven 2Y/5Y/10Y/30Y"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Uses breakeven identity."},
    {"section": "02", "module_id": "rate_attribution", "title": "Rate Attribution",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Selectable tenor and window."},
    {"section": "02", "module_id": "curve_decomp", "title": "2s10s Curve Decomposition",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Identity residual = zero."},

    # ── 03 · Curve Regimes ──
    {"section": "03", "module_id": "curve_regimes", "title": "Curve regime matrix",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/curve_regimes.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "10D window, 6 pairs."},

    # ── 04 · Global Rates ──
    {"section": "04", "module_id": "global_10y", "title": "Global 10Y overlay & slope ranking",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/global_rates.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["2Y/5Y/10Y/30Y for US/DE/JP/UK/CA/AU/CH"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Seven-country overview including Switzerland."},
    {"section": "04", "module_id": "country_boards", "title": "Country rate boards",
     "app_section": "04b", "reference_section": "04 · Global Rates",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/country_rate_boards.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["2Y/5Y/10Y/30Y nominal curves for US/DE/JP/UK/CA/AU/CH"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Fully aligned nominal country boards with yield changes, slopes, "
                    "percentiles and descriptive curve-move readings. No forward-fill."},
    {"section": "04", "module_id": "global_real_inflation_attribution",
     "title": "Country real-rate / inflation-compensation attribution",
     "app_section": "04b", "reference_section": "04 · Global Rates",
     "current_status": "Partial", "do_not_fake": False,
     "implemented_in": "models/global_rate_decomposition.py",
     "evidence_basis": "DATA.xlsx exact-tenor nominal and real government yields",
     "data_source_status": "partial",
     "can_render_real_chart": True,
     "required_data": ["Same-tenor nominal yield", "Same-market inflation-linked real yield"],
     "missing_data": ["Switzerland has no confirmed real-yield series in DATA.xlsx"],
     "recommended_priority": 0,
     "build_notes": "Live for US/DE/JP/UK/CA/AU on exact common dates. Switzerland is "
                    "shown as unavailable; no euro-area or other-country proxy is used."},

    # ── 05 · Cross-Asset ──
    {"section": "05", "module_id": "ca_8regime", "title": "Cross-Asset 8-regime timeline",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/cross_asset/directional.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX", "USGG10YR INDEX", "DXY CURNCY"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "20D/21D vol-scaled."},
    {"section": "05", "module_id": "market_linkage", "title": "Market Linkage & Correlations",
     "app_section": "05b", "reference_section": "05 · Cross-Asset Regimes / Market Linkage",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/market_linkage.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX", "USGG10YR INDEX", "DXY CURNCY"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Reference-pack-aligned one-trade gauge: rolling 63D PC1 explained variance across SPX, UST 10Y and DXY, with the three underlying 20D pairwise correlations. Descriptive, not causal."},

    # ── 06 · Equities & Earnings ──
    {"section": "06", "module_id": "sector_rotation", "title": "Sector rotation & breadth",
     "app_section": "06", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/sector_rotation.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX", "SPX_Sector_Weights"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive sector rotation, breadth, dispersion, and "
                    "weight-context monitor. Not official SPX return attribution."},
    {"section": "06", "module_id": "breadth", "title": "Sector breadth & dispersion",
     "app_section": "06", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/sector_rotation.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Positive breadth, SPX-outperform breadth, cross-sectional "
                    "dispersion. Denominator reflects actual valid sectors."},
    {"section": "06", "module_id": "spx_sector_contribution", "title": "SPX sector contribution estimate",
     "app_section": "06b", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/sector_contribution.py",
     "evidence_basis": "DATA.xlsx + implemented approximation", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX", "SPX_Sector_Weights"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live transparent estimate using the latest periodic weight available "
                    "on or before each return-window start date × sector simple return, "
                    "with explicit residual. Not official SPX attribution."},
    {"section": "06", "module_id": "spx_sector", "title": "Official SPX sector attribution",
     "app_section": None, "reference_section": "06 · Equities & Earnings",
     "current_status": "Not Started", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "methodology required", "data_source_status": "methodology required",
     "can_render_real_chart": False,
     "required_data": ["Daily-weight methodology or official contribution data"],
     "missing_data": [], "recommended_priority": 4,
     "build_notes": "Requires divisor-consistent index treatment or official contribution "
                    "data. Not equivalent to the descriptive rotation monitor."},
    {"section": "06", "module_id": "earnings_val", "title": "Global FY1 earnings & valuation",
     "app_section": "06c", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/earnings_valuation.py",
     "evidence_basis": "DATA.xlsx + user-confirmed Bloomberg formula",
     "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX Index level", "BEST_EPS", "BEST_FPERIOD_OVERRIDE=1FY"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live weekly FY1 EPS and implied FY1 P/E monitor. Main split uses the exact log identity: index return = EPS growth + P/E change. Includes a clearly labelled 26-week OLS diagnostic; not fair value, forecast, or the reference pack's 3-year daily regression."},
    {"section": "06", "module_id": "forward_vs_realized_eps", "title": "Forward estimate vs realized EPS",
     "app_section": None, "reference_section": "06 · Equities & Earnings",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "realized EPS field not supplied", "data_source_status": "missing",
     "can_render_real_chart": False,
     "required_data": ["Confirmed realized/trailing EPS series comparable with FY1 estimate"],
     "missing_data": ["Realized or trailing EPS field and period definition"],
     "recommended_priority": 4,
     "build_notes": "The live FY1 monitor does not compare forecasts with realized EPS because no confirmed realized/trailing EPS series is present."},

    # ── 07 · FX ──
    {"section": "07", "module_id": "fx_eurusd", "title": "EURUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['EURUSD spot', 'DE 2Y nom', 'US 2Y nom', 'DE 10Y nom', 'US 10Y nom', 'DE 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "07", "module_id": "fx_usdjpy", "title": "USDJPY rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['USDJPY spot', 'US 2Y nom', 'JP 2Y nom', 'US 10Y nom', 'JP 10Y nom', 'US 10Y real', 'JP 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "07", "module_id": "fx_gbpusd", "title": "GBPUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['GBPUSD spot', 'UK 2Y nom', 'US 2Y nom', 'UK 10Y nom', 'US 10Y nom', 'UK 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "07", "module_id": "fx_audusd", "title": "AUDUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['AUDUSD spot', 'AU 2Y nom', 'US 2Y nom', 'AU 10Y nom', 'US 10Y nom', 'AU 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},

    # ── Experimental / Appendix ──
    {"section": "A1", "module_id": "global_scoring", "title": "Global Scoring (Appendix)",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/scoring/",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Scoring sheets"], "missing_data": [], "recommended_priority": 0,
     "build_notes": "Standalone appendix."},

    # ── CLI Correlations ──
    {"section": "00", "module_id": "cli_spx_corr",
     "title": "CLI vs SPX rolling correlation",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/cli_correlations.py, charts/pages/liquidity_overview.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX (have)", "Composite Liquidity Index (have)"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "20D rolling correlation. Live sanity-check target."},
    {"section": "00", "module_id": "cli_hsi_corr",
     "title": "CLI vs HSI rolling correlation",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": "models/cli_correlations.py (code ready, awaiting data)",
     "evidence_basis": "implemented model, awaiting data", "data_source_status": "missing",
     "can_render_real_chart": False,
     "required_data": ["HSI INDEX (Hang Seng daily close)", "Composite Liquidity Index (have)"],
     "missing_data": ["HSI INDEX — not in DATA.xlsx Sheet1"],
     "recommended_priority": 1,
     "build_notes": "20D rolling correlation. Add HSI INDEX to Bloomberg BDH pull. Code is ready."},
    {"section": "00", "module_id": "cli_btc_corr",
     "title": "CLI vs Bitcoin rolling correlation",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": "models/cli_correlations.py (code ready, awaiting data)",
     "evidence_basis": "implemented model, awaiting data", "data_source_status": "missing",
     "can_render_real_chart": False,
     "required_data": ["XBTUSD BGN Curncy or equivalent BTC daily close", "Composite Liquidity Index (have)"],
     "missing_data": ["Bitcoin price — not in DATA.xlsx Sheet1"],
     "recommended_priority": 1,
     "build_notes": "20D rolling correlation. Add XBTUSD BGN Curncy to Bloomberg BDH pull. Code is ready."},
]


def by_status(status: str) -> list[dict]:
    return [m for m in ROADMAP if m["current_status"] == status]

def coverage_summary() -> dict:
    counts = {}
    for m in ROADMAP:
        s = m["current_status"]
        counts[s] = counts.get(s, 0) + 1
    return counts

def do_not_fake_list() -> list[dict]:
    return [m for m in ROADMAP if m.get("do_not_fake")]


# Methodology questions deliberately parked for later research.  These are not
# implementation instructions: the live model keeps its current settings until
# evidence, historical validation, and an explicit model decision support a
# change.
METHODOLOGY_RESEARCH_BACKLOG: list[dict] = [
    {
        "topic": "Bucket weights",
        "question": "Why should the five buckets use 30/20/20/20/10 weights?",
        "current_treatment": "First-version judgement weights; not statistically estimated.",
        "research_needed": "Compare equal weights, PCA/statistical weights and outcome-calibrated weights; test stability and concentration.",
        "status": "Deferred research",
    },
    {
        "topic": "Regime thresholds",
        "question": "Why should 60+ be Loose, below 45 Tight and below 35 Stress?",
        "current_treatment": "Provisional display thresholds; not empirically calibrated economic boundaries.",
        "research_needed": "Calibrate against historical percentiles, funding-stress episodes and documented market events.",
        "status": "Deferred research",
    },
    {
        "topic": "Missing-bucket weights",
        "question": "Should weights be fully renormalised when a bucket becomes unavailable?",
        "current_treatment": "Qualifying buckets receive the unavailable bucket's weight pro rata.",
        "research_needed": "Compare fixed-weight, partial-publication and renormalised variants; separate market moves from coverage effects.",
        "status": "Deferred research",
    },
    {
        "topic": "Historical event validation",
        "question": "Do the chosen settings identify historical liquidity events reliably?",
        "current_treatment": "No completed event-study or out-of-sample validation is claimed.",
        "research_needed": "Define an event set and evaluation metrics, then test signal timing, false positives and robustness across vintages.",
        "status": "Deferred research",
    },
]

BUILD_PRIORITIES = {
    0: "Already built",
    1: "Priority 1 — enhance with existing data",
    2: "Priority 2 — enhance implemented country analytics",
    3: "Priority 3 — FX differential (data now available)",
    4: "Priority 4 — equities/sector (data now available)",
    5: "Priority 5 — futures path (needs contract metadata)",
}
