"""
config/model_roadmap.py
=======================
Structured registry of PDF-style content modules with traceability fields.

Every item includes evidence_basis, data_source_status, and can_render_real_chart.
"""
from __future__ import annotations

ROADMAP: list[dict] = [
    # ── 00 · Liquidity ──
    {"section": "00", "module_id": "cli_index", "title": "Composite Liquidity Index",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "index/composite.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SOFR", "EFFR", "IORB", "IG OAS", "HY OAS", "Fed reserves"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Core proprietary model. Do not modify."},

    # ── 01 · Policy ──
    {"section": "01", "module_id": "policy_spot", "title": "Policy spot rates & funding spreads",
     "current_status": "Partial", "do_not_fake": False,
     "implemented_in": "models/policy_short_rates.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SOFR", "EFFR", "IORB"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live for spot rates. FOMC path/SOFR strip still missing."},
    {"section": "01", "module_id": "fomc_path", "title": "FOMC implied policy path",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "roadmap only", "data_source_status": "partial",
     "can_render_real_chart": False,
     "required_data": ["FF futures", "FOMC calendar", "EFFR"],
     "missing_data": ["FOMC meeting calendar", "Contract metadata/conventions"],
     "recommended_priority": 5,
     "build_notes": "FF1/FF2/FF3 data now in Sheet1 but model not implemented. Needs contract conventions."},
    {"section": "01", "module_id": "sofr_strip", "title": "SOFR futures strip",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "roadmap only", "data_source_status": "partial",
     "can_render_real_chart": False,
     "required_data": ["SFR futures by expiry", "Contract metadata"],
     "missing_data": ["Contract month mapping", "Price-to-rate convention"],
     "recommended_priority": 5,
     "build_notes": "SFR1/SFR2/SFR3 data now in Sheet1 but model not implemented."},

    # ── 02 · Rate Decomposition ──
    {"section": "02", "module_id": "us_curve_complex", "title": "US Curve Complex",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["US nominal 2Y/5Y/10Y/30Y", "US breakeven 2Y/5Y/10Y/30Y"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Uses breakeven identity."},
    {"section": "02", "module_id": "rate_attribution", "title": "Rate Attribution",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Selectable tenor and window."},
    {"section": "02", "module_id": "curve_decomp", "title": "2s10s Curve Decomposition",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/rate_decomposition.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Identity residual = zero."},

    # ── 03 · Curve Regimes ──
    {"section": "03", "module_id": "curve_regimes", "title": "Curve regime matrix",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/curve_regimes.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Same as US Curve Complex"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "10D window, 6 pairs."},

    # ── 04 · Global Rates ──
    {"section": "04", "module_id": "global_10y", "title": "Global 10Y overlay & slope ranking",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/global_rates.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["2Y/5Y/10Y/30Y for US/DE/JP/UK/CA/AU"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "CH now also available with merged data."},
    {"section": "04", "module_id": "country_boards", "title": "Country boards",
     "current_status": "Not Started", "do_not_fake": False,
     "implemented_in": None,
     "evidence_basis": "roadmap only", "data_source_status": "available",
     "can_render_real_chart": False,
     "required_data": ["Country nominal curves"],
     "missing_data": [], "recommended_priority": 2,
     "build_notes": "Nominal-only feasible now. Non-US real/BE data also available for some countries."},

    # ── 05 · Cross-Asset ──
    {"section": "05", "module_id": "ca_8regime", "title": "Cross-Asset 8-regime timeline",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/cross_asset/directional.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX", "USGG10YR INDEX", "DXY CURNCY"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "20D/21D vol-scaled."},
    {"section": "05", "module_id": "market_linkage", "title": "Market Linkage PCA",
     "current_status": "Experimental", "do_not_fake": False,
     "implemented_in": "models/cross_asset/",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX", "USGG10YR INDEX", "DXY CURNCY"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "63D PCA / 20D correlations."},

    # ── 06 · Equities & Earnings ──
    {"section": "06", "module_id": "sector_rotation", "title": "Sector rotation & breadth",
     "app_section": "06", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/sector_rotation.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX", "SPX_Sector_Weights"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive sector rotation, breadth, dispersion, and "
                    "weight-context monitor. Not official SPX return attribution."},
    {"section": "06", "module_id": "breadth", "title": "Sector breadth & dispersion",
     "app_section": "06", "reference_section": "06 · Equities & Earnings",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/sector_rotation.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Positive breadth, SPX-outperform breadth, cross-sectional "
                    "dispersion. Denominator reflects actual valid sectors."},
    {"section": "06", "module_id": "spx_sector_contribution", "title": "SPX sector contribution estimate",
     "app_section": None, "reference_section": "06 · Equities & Earnings",
     "current_status": "Not Started", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "methodology required", "data_source_status": "available",
     "can_render_real_chart": False,
     "required_data": ["11 S&P 500 sector indices", "SPX INDEX", "SPX_Sector_Weights"],
     "missing_data": [], "recommended_priority": 3,
     "build_notes": "Approximation (start-period weight × sector return) with residual "
                    "reconciliation test. Requires validated methodology."},
    {"section": "06", "module_id": "spx_sector", "title": "Official SPX sector attribution",
     "app_section": None, "reference_section": "06 · Equities & Earnings",
     "current_status": "Not Started", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "methodology required", "data_source_status": "methodology required",
     "can_render_real_chart": False,
     "required_data": ["Daily-weight methodology or official contribution data"],
     "missing_data": [], "recommended_priority": 4,
     "build_notes": "Requires divisor-consistent index treatment or official contribution "
                    "data. Not equivalent to the descriptive rotation monitor."},
    {"section": "06", "module_id": "earnings_val", "title": "Earnings vs valuation",
     "app_section": None, "reference_section": "06 · Equities & Earnings",
     "current_status": "Needs confirmation", "do_not_fake": True,
     "implemented_in": None,
     "evidence_basis": "needs confirmation", "data_source_status": "needs confirmation",
     "can_render_real_chart": False,
     "required_data": ["SPX forward EPS", "SPX trailing EPS or PE"],
     "missing_data": ["Field meanings not confirmed in workbook"],
     "recommended_priority": 4,
     "build_notes": "Check if EPS/PE columns exist and meanings are documented."},

    # ── 07 · FX ──
    {"section": "06", "module_id": "fx_eurusd", "title": "EURUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['EURUSD spot', 'DE 2Y nom', 'US 2Y nom', 'DE 10Y nom', 'US 10Y nom', 'DE 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "06", "module_id": "fx_usdjpy", "title": "USDJPY rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['USDJPY spot', 'US 2Y nom', 'JP 2Y nom', 'US 10Y nom', 'JP 10Y nom', 'US 10Y real', 'JP 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "06", "module_id": "fx_gbpusd", "title": "GBPUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['GBPUSD spot', 'UK 2Y nom', 'US 2Y nom', 'UK 10Y nom', 'US 10Y nom', 'UK 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},
    {"section": "06", "module_id": "fx_audusd", "title": "AUDUSD rate differential",
     "app_section": "07", "reference_section": "07 · FX",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/fx_rate_differential.py",
     "evidence_basis": "DATA.xlsx + implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ['AUDUSD spot', 'AU 2Y nom', 'US 2Y nom', 'AU 10Y nom', 'US 10Y nom', 'AU 10Y real', 'US 10Y real'],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "Live descriptive rate-differential monitor. Uses fully aligned spot, 2Y nom, 10Y nom, 10Y real."},

    # ── Experimental / Appendix ──
    {"section": "02b", "module_id": "rates_pca", "title": "Rates Complex PCA",
     "current_status": "Experimental", "do_not_fake": False,
     "implemented_in": "models/rates_complex/",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["FICC columns"], "missing_data": [], "recommended_priority": 0,
     "build_notes": "Separate from PDF-style decomposition."},
    {"section": "06b", "module_id": "fx_pca", "title": "FX Complex PCA",
     "current_status": "Experimental", "do_not_fake": False,
     "implemented_in": "models/fx_complex/",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["DXY, FXJPEMCS, JYBSS12M"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "NOT the rate-differential FX model."},
    {"section": "A1", "module_id": "global_scoring", "title": "Global Scoring (Appendix)",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/scoring/",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["Scoring sheets"], "missing_data": [], "recommended_priority": 0,
     "build_notes": "Standalone appendix."},

    # ── CLI Correlations ──
    {"section": "00", "module_id": "cli_spx_corr",
     "title": "CLI vs SPX rolling correlation",
     "current_status": "Live", "do_not_fake": False,
     "implemented_in": "models/cli_correlations.py, charts/pages/liquidity_overview.py",
     "evidence_basis": "implemented model", "data_source_status": "available",
     "can_render_real_chart": True,
     "required_data": ["SPX INDEX (have)", "Composite Liquidity Index (have)"],
     "missing_data": [], "recommended_priority": 0,
     "build_notes": "20D rolling correlation. Live sanity-check target."},
    {"section": "00", "module_id": "cli_hsi_corr",
     "title": "CLI vs HSI rolling correlation",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": "models/cli_correlations.py (code ready, awaiting data)",
     "evidence_basis": "implemented model, awaiting data", "data_source_status": "missing",
     "can_render_real_chart": False,
     "required_data": ["HSI INDEX (Hang Seng daily close)", "Composite Liquidity Index (have)"],
     "missing_data": ["HSI INDEX — not in DATA.xlsx Sheet1"],
     "recommended_priority": 1,
     "build_notes": "20D rolling correlation. Add HSI INDEX to Bloomberg BDH pull. Code is ready."},
    {"section": "00", "module_id": "cli_btc_corr",
     "title": "CLI vs Bitcoin rolling correlation",
     "current_status": "Data Missing", "do_not_fake": True,
     "implemented_in": "models/cli_correlations.py (code ready, awaiting data)",
     "evidence_basis": "implemented model, awaiting data", "data_source_status": "missing",
     "can_render_real_chart": False,
     "required_data": ["XBTUSD BGN Curncy or equivalent BTC daily close", "Composite Liquidity Index (have)"],
     "missing_data": ["Bitcoin price — not in DATA.xlsx Sheet1"],
     "recommended_priority": 1,
     "build_notes": "20D rolling correlation. Add XBTUSD BGN Curncy to Bloomberg BDH pull. Code is ready."},
]


def by_status(status: str) -> list[dict]:
    return [m for m in ROADMAP if m["current_status"] == status]

def coverage_summary() -> dict:
    counts = {}
    for m in ROADMAP:
        s = m["current_status"]
        counts[s] = counts.get(s, 0) + 1
    return counts

def do_not_fake_list() -> list[dict]:
    return [m for m in ROADMAP if m.get("do_not_fake")]

BUILD_PRIORITIES = {
    0: "Already built",
    1: "Priority 1 — enhance with existing data",
    2: "Priority 2 — country boards",
    3: "Priority 3 — FX differential (data now available)",
    4: "Priority 4 — equities/sector (data now available)",
    5: "Priority 5 — futures path (needs contract metadata)",
}
